// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class Cliente {
  final PlatformInt64 id;
  final String nome;
  final String cadastro;
  final Endereco endereco;
  final String telefone;

  const Cliente({
    required this.id,
    required this.nome,
    required this.cadastro,
    required this.endereco,
    required this.telefone,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      nome.hashCode ^
      cadastro.hashCode ^
      endereco.hashCode ^
      telefone.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Cliente &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          nome == other.nome &&
          cadastro == other.cadastro &&
          endereco == other.endereco &&
          telefone == other.telefone;
}

class Endereco {
  final String cep;
  final String logradouro;
  final String numero;
  final String? complemento;
  final String bairro;
  final String municipio;
  final String uf;

  const Endereco({
    required this.cep,
    required this.logradouro,
    required this.numero,
    this.complemento,
    required this.bairro,
    required this.municipio,
    required this.uf,
  });

  @override
  int get hashCode =>
      cep.hashCode ^
      logradouro.hashCode ^
      numero.hashCode ^
      complemento.hashCode ^
      bairro.hashCode ^
      municipio.hashCode ^
      uf.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Endereco &&
          runtimeType == other.runtimeType &&
          cep == other.cep &&
          logradouro == other.logradouro &&
          numero == other.numero &&
          complemento == other.complemento &&
          bairro == other.bairro &&
          municipio == other.municipio &&
          uf == other.uf;
}
