// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class ItemPedido {
  final PlatformInt64 idItem;
  final String produtoNome;
  final PlatformInt64 quantidade;
  final double valor;
  final double subtotal;

  const ItemPedido({
    required this.idItem,
    required this.produtoNome,
    required this.quantidade,
    required this.valor,
    required this.subtotal,
  });

  @override
  int get hashCode =>
      idItem.hashCode ^
      produtoNome.hashCode ^
      quantidade.hashCode ^
      valor.hashCode ^
      subtotal.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ItemPedido &&
          runtimeType == other.runtimeType &&
          idItem == other.idItem &&
          produtoNome == other.produtoNome &&
          quantidade == other.quantidade &&
          valor == other.valor &&
          subtotal == other.subtotal;
}

class Pedido {
  final PlatformInt64 id;
  final PlatformInt64 clienteId;
  final List<ItemPedido> itens;
  final double valorTotal;
  final String data;

  const Pedido({
    required this.id,
    required this.clienteId,
    required this.itens,
    required this.valorTotal,
    required this.data,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      clienteId.hashCode ^
      itens.hashCode ^
      valorTotal.hashCode ^
      data.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Pedido &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          clienteId == other.clienteId &&
          itens == other.itens &&
          valorTotal == other.valorTotal &&
          data == other.data;
}

class Produto {
  final PlatformInt64 idMerc;
  final String nomeMerc;
  final PlatformInt64 quantidadeEst;

  const Produto({
    required this.idMerc,
    required this.nomeMerc,
    required this.quantidadeEst,
  });

  @override
  int get hashCode =>
      idMerc.hashCode ^ nomeMerc.hashCode ^ quantidadeEst.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Produto &&
          runtimeType == other.runtimeType &&
          idMerc == other.idMerc &&
          nomeMerc == other.nomeMerc &&
          quantidadeEst == other.quantidadeEst;
}
