// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../error.dart';
import '../frb_generated.dart';
import '../models/cliente.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `checagem_presenca_dados`

Future<void> incluirClienteService({required Cliente cliente}) => RustLib
    .instance
    .api
    .crateApiClientesServiceIncluirClienteService(cliente: cliente);

Future<void> atualizarClienteService({
  required Cliente cliente,
  required PlatformInt64 clienteId,
}) => RustLib.instance.api.crateApiClientesServiceAtualizarClienteService(
  cliente: cliente,
  clienteId: clienteId,
);

Future<void> excluirClienteService({
  required Cliente cliente,
  required PlatformInt64 clienteId,
}) => RustLib.instance.api.crateApiClientesServiceExcluirClienteService(
  cliente: cliente,
  clienteId: clienteId,
);
