// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../error.dart';
import '../frb_generated.dart';
import '../models/pedido.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<void> entradaNoEstoqueService({required Produto produto}) => RustLib
    .instance
    .api
    .crateApiEstoqueServiceEntradaNoEstoqueService(produto: produto);

Future<List<Produto>> listagemDoEstoqueService() =>
    RustLib.instance.api.crateApiEstoqueServiceListagemDoEstoqueService();

Future<void> incluirItemEstoqueService({
  required String nomeMerc,
  required PlatformInt64 quantidadeEst,
}) => RustLib.instance.api.crateApiEstoqueServiceIncluirItemEstoqueService(
  nomeMerc: nomeMerc,
  quantidadeEst: quantidadeEst,
);

Future<void> excluirItemEstoqueService({required PlatformInt64 itemId}) =>
    RustLib.instance.api.crateApiEstoqueServiceExcluirItemEstoqueService(
      itemId: itemId,
    );
