// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../error.dart';
import '../frb_generated.dart';
import '../models/pedido.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<void> novoPedidoService({
  required Pedido pedido,
  required List<ItemPedido> itens,
}) => RustLib.instance.api.crateApiPedidosServiceNovoPedidoService(
  pedido: pedido,
  itens: itens,
);

Future<List<Pedido>> listarPedidosService() =>
    RustLib.instance.api.crateApiPedidosServiceListarPedidosService();

Future<void> excluirPedidoService({required PlatformInt64 pedidoId}) => RustLib
    .instance
    .api
    .crateApiPedidosServiceExcluirPedidoService(pedidoId: pedidoId);
